#!/usr/bin/env sh

# backup zshrc
cp ~/.zshrc $(pwd)/dot_files/

# add
git add --all

# commit
update_at=$(date +"%Y-%m-%d %H:%M:%S")
git commit -am "update at $update_at"

# push
git push origin master